[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TaylorIntegration = "92b13dbe-c966-51a2-8445-caca9f8a7d42"
